// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCase1() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(655, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.cssSelector(".oxd-button")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("Dashboard"));
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h5")).getText(), is("System Users"));
    driver.findElement(By.cssSelector(".oxd-userdropdown-icon")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void testCase2() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text")).click();
    driver.findElement(By.cssSelector(".oxd-topbar-body-nav-tab:nth-child(3) > .oxd-topbar-body-nav-tab-item")).click();
    driver.findElement(By.linkText("General Information")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("General Information"));
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(2) .oxd-text")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h5")).getText(), is("Employee Information"));
    driver.findElement(By.cssSelector(".oxd-userdropdown-icon")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void testCase3() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(2) .oxd-text")).click();
    driver.findElement(By.linkText("Add Employee")).click();
    driver.findElement(By.cssSelector(".orangehrm-main-title")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Add Employee"));
    driver.findElement(By.linkText("Reports")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h5")).getText(), is("Employee Reports"));
    driver.findElement(By.cssSelector(".oxd-userdropdown-icon")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void testCase4() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.linkText("PIM")).click();
    driver.findElement(By.cssSelector(".\\--parent > .oxd-topbar-body-nav-tab-item")).click();
    driver.findElement(By.linkText("Optional Fields")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Optional Fields"));
    driver.findElement(By.cssSelector(".bi-chevron-down")).click();
    driver.findElement(By.linkText("Custom Fields")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Custom Fields"));
    driver.findElement(By.cssSelector(".bi-chevron-down")).click();
    driver.findElement(By.linkText("Data Import")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Data Import"));
    driver.findElement(By.cssSelector(".bi-chevron-down")).click();
    driver.findElement(By.linkText("Reporting Methods")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Reporting Methods"));
    driver.findElement(By.cssSelector(".\\--parent > .oxd-topbar-body-nav-tab-item")).click();
    driver.findElement(By.linkText("Termination Reasons")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Termination Reasons"));
    driver.findElement(By.cssSelector(".bi-caret-down-fill")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void testCase5() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".bi-caret-down-fill")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("username")).sendKeys("asd");
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("password")).sendKeys("qwee");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    assertThat(driver.findElement(By.cssSelector(".oxd-alert-content-text")).getText(), is("Invalid credentials"));
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("username")).sendKeys("52653623");
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("password")).sendKeys("uywet7we7we");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    assertThat(driver.findElement(By.cssSelector(".oxd-alert-content-text")).getText(), is("Invalid credentials"));
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("password")).sendKeys("aaaaaaaaasdd");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    assertThat(driver.findElement(By.cssSelector(".oxd-alert-content-text")).getText(), is("Invalid credentials"));
    driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
    driver.findElement(By.name("username")).sendKeys("qwqeqeqe");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    assertThat(driver.findElement(By.cssSelector(".oxd-alert-content-text")).getText(), is("Invalid credentials"));
    driver.close();
  }
}
