// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void terminationReasons() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.linkText("PIM")).click();
    driver.findElement(By.cssSelector(".\\--parent")).click();
    driver.findElement(By.linkText("Termination Reasons")).click();
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("illness");
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(4) .oxd-icon-button:nth-child(1) > .oxd-icon")).click();
    driver.findElement(By.cssSelector(".oxd-button--label-danger")).click();
    driver.findElement(By.cssSelector(".bi-caret-down-fill")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void terminationReasonVerify() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(654, 672));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("Dashboard"));
    driver.findElement(By.cssSelector(".bi-list")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(2) .oxd-text")).click();
    driver.findElement(By.cssSelector(".\\--parent > .oxd-topbar-body-nav-tab-item")).click();
    driver.findElement(By.linkText("Termination Reasons")).click();
    assertThat(driver.findElement(By.cssSelector(".orangehrm-main-title")).getText(), is("Termination Reasons"));
    driver.findElement(By.cssSelector(".bi-caret-down-fill")).click();
    driver.findElement(By.linkText("Logout")).click();
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h5")).getText(), is("Login"));
    driver.close();
  }
}
